spring:
  application:
    name: backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: lldj123414
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org.springframework.security: DEBUG

naver:
  client-id: "네이버 API 클라이언트 아이디 입력"
  client-secret: "네이버 API 클라이언트 시크릿 입력"
  book-search-url: "https://openapi.naver.com/v1/search/book.json"